export const menuData = {
  Viski: [
    { name: `Arran` },
    { name: `Ballentine's` },
    { name: 'Chivas Regal' },
    { name: `Dalmore` },
    { name: `Bunnahabhain` },
    { name: `Jack Daniel's` },
    { name: `Lagavulin` },
    { name: 'Macallan' },
    { name: 'Kavalan' },
    { name: `Bruichladdich` },
    { name: 'J&B' },
    { name: 'Johnnie Walker' },
    { name: 'Talisker' },
    { name: `Jameson` },
    { name: `Royal Salute` },
    { name: `Monkey Shoulder` },
  ],
  Rakı: [
    { name: 'Yeni Rakı' },
    { name: 'Beylerbeyi' },
    { name: 'Tekirdağ' },
    { name: 'Efe' },
    { name: 'Altınbaş' },
    { name: 'Anason' },
    { name: 'Sarıkız' },
    { name: 'Kulüp Rakı' },
  ],
  Votka: [
    { name: 'Absolut' },
    { name: 'Smirnoff' },
    { name: 'İstanblue' },
    { name: 'Grey Goose' },
    { name: 'Ciroc' },
    { name: 'Belvedere' },
  ],
  Cin: [
    { name: `Hendrick's` },
    { name: `Gordon's` },
    { name: `Gilbey` },
    { name: `Beefeater` },
    { name: `Tanqueray` },
    { name: `Monkey 47` },
    { name: `Roku Gin` },
  ],
  Tekila: [
    { name: 'Olmeca' },
    { name: 'Sauza' },
    { name: 'Espolon' },
    { name: 'Herradura' },
  ],
  Likör: [
    { name: 'Jägermeister' },
    { name: 'Baileys' },
    { name: 'Captain Morgan' },
    { name: `Sheridan's` },
  ],
  Bira: [
    { name: 'Efes Pilsen' },
    { name: 'Miller' },
    { name: 'Carlsberg' },
    { name: 'Bomonti' },
    { name: 'Heineken' },
  ],
  Mezeler: [
    { name: 'Patates Kızartması' },
    { name: 'Soğan Halkası' },
    { name: 'Haydari' },
    { name: 'Şakşuka' },
    { name: 'Kaşarlı Mantar' },
    { name: 'Atom' },
    { name: 'Humus' },
    { name: 'Karides' },
    { name: 'Peynir Tabağı (Beyaz, Eski Kaşar)' },
    { name: 'Çerez Çeşitleri' },
    { name: 'Cips' },
    { name: 'Meyve çeşitleri' },
  ],
};
